# Generated by Django 5.1.2 on 2024-11-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app_celery', '0002_uploadedimage_uploaded_at_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
